# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'picture_poster' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
end
